language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mukulkumra/docker-react-project -f Dockerfile.dev .
script:
  - docker run -e CI=true mukulkumra/docker-react-project npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-326047679654"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
