language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mukulkumra/docker-react-project -f Dockerfile.dev .
script:
  - docker run -e CI=true mukulkumra/docker-react-project npm run test -- --coverage

